# Generated by Django 3.0.7 on 2020-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0003_auto_20200724_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
