# Generated by Django 3.0.7 on 2020-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
    ]
