# Generated by Django 3.0.7 on 2020-07-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0007_wishlist_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Society',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
